# Site settings
title: 徐嘉乐作品集
# header-img: "img/Xacebook.jpg"
tagline: "cn"  
description: "徐嘉乐作品集"  
baseurl: ""
url: "https://xujiale-china.github.io/"  

# About/contact
owner: 
  name: "徐嘉乐"
  email: xujiale0224@gmail.com
  bio: "徐嘉乐作品集"

# Data
gavatar: img/favicon64.png
favicon: img/favicon64.png

douban_username: cnfeat
twitter_username: feat
github_username: cnfeat
facebook_username: 
weibo_username: cnfeat 
zhihu_username: feat

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "CNFeat"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 


# Analytics and webmaster tools stuff goes here
google_analytics: UA-80884545-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation